### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by HamiltonGerlach** [elpollodiablo84/atom-matlab-editor#7]
Hello there,

the plugin throws this error twice when executing the selection via F9.

1. Installed according to readme, matlabroot/bin/win64 is on PATH, 'atom-matlab-editor\lib\java' is on MATLAB search path. Using R2019b.
2. Tested with a simple disp('hi') in atom, error occurs.
3. The MATLAB command window shows the disp('hi') statement, but not the output 'hi'.

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Windows 10
**Thrown From**: [atom-matlab-editor](https://github.com/elpollodiablo84/atom-matlab-editor) package 0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At C:\Users\ScottCirrus\.atom\packages\atom-matlab-editor\lib\atom-matlab-editor.js:406

TypeError: Cannot read property 'split' of undefined
    at collectAllErrors (/packages/atom-matlab-editor/lib/atom-matlab-editor.js:406:38)
    at Socket.e.on.e (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:1123714)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:260:13)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

### Commands

```
  3x -3:06.9.0 atom-matlab-editor:run-selection (input.hidden-input)
```

### Non-Core Packages

```
atom-hydra 0.2.14 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-matlab-editor 0.3.0 
atom-python-run 0.9.7 
autocomplete-glsl 0.2.3 
busy-signal 2.0.1 
custom-folds 1.9.5 
file-watcher 2.0.0 
Hydrogen 2.14.1 
intentions 1.1.5 
language-glsl 2.0.4 
language-latex 1.2.0 
language-matlab-plus 1.12.0 
latex 0.50.2 
line-count 0.5.2 
line-count-status 0.0.3 
linter 2.3.1 
linter-glslify 1.0.0 
linter-matlab 1.3.0 
linter-ui-default 1.8.1 
minimap 4.29.9 
minimap-cursorline 0.2.0 
minimap-hide 0.3.0 
minimap-linter 2.2.1 
script 3.26.0 
veda 2.13.1 
zentabs 0.8.9 
```

**Comment by elpollodiablo84** [comment]
From the stack trace, this issue appears when parsing a Matlab error. Could you try executing the command directly in the Matlab command window, without Atom? First check that this issue is still there clearly.

Let me know what happens, since I can't reproduce it. Anyway, I clearly have to make the error parsing more robust, so thanks in advance!

**Comment by HamiltonGerlach** [comment]
![image](https://user-images.githubusercontent.com/37122852/81108296-c8daf000-8f18-11ea-9f21-d4dc16ad891d.png)

Well, when executing it directly in the command window, it just works as it should. I have attached a screenshot of the test, first executing from the MATLAB Cmd and the second time from Atom.

I suspect the issue is related to R2019b, since this package works fine on my other work environment using R2017b.

**Comment by elpollodiablo84** [comment]
> I suspect the issue is related to R2019b, since this package works fine on my other work environment using R2017b.

You probably found a clue: in Matlab 2019b something changed in the way Matlab handles global/local/nested function, as stated in [this](https://it.mathworks.com/help/matlab/matlab_prog/upgrade-code-for-r2019b-changes-to-function-precedence-order.html). The "Run selection" (`F9`) function uses, in fact, a combination of `evalin` and `run`, both impacted by the changes.

To test this hypothesis, I have to ask you to do the following (if you can):
1. Create a new script, let's say `test.m`, in your working directory with only the `disp('hi')` statement.
2. Execute in Matlab (without Atom) the command `runInFolder('test.m', pwd)`. It _should_ throw an error hopefully, let me know what happens. By the way, `runInFolder` is a simple function created by me and used to execute "Run selection/section" commands from Atom. It's already in your search path because it's in `atom-matlab-editor\lib\java`.

Unfortunately I can't use R2019b, so thanks in advance for your time!

**Comment by HamiltonGerlach** [comment]
Alright, I tested the above and it doesn't throw an error.

The error in atom-matlab-editor.runSelection reads as follows:

> at com.mathworks.engine.FutureResult.get(FutureResult.java:59)
> at com.mathworks.engine.MatlabEngine.eval(MatlabEngine.java:373)
> at javaMatlabConnect.main(javaMatlabConnect.java:65)
> 
> Caused by: com.mathworks.mvm.exec.MvmCompileException: Error: Invalid expression. Check for missing or extra characters. ... 3 more com.mathworks.mvm.exec.MvmCompileException: Error: Invalid expression. Check for missing or extra characters. Error in ==> E:\MATLAB\toolbox\matlab\lang\run.m>run at 91 Error in ==> C:\Users\ScottCirrus.atom\packages\atom-matlab-editor\lib\java\runInFolder.m>runInFolder at 5

I investigated further into run.m - Line 91 is the command which executes the temp .m file:

`evalin('caller', strcat(script, ';'));`

The script file has the following name `AME_-5172-78LUShmUQMZM-.m`. Executing the line gives:

```
Error: Invalid expression. Check for missing multiplication
operator, missing or unbalanced delimiters, or other syntax
error. To construct matrices, use brackets instead of
parentheses.
```

I removed the underscores and dashes from the script name (and renamed the file accordingly), after which the command works:

```
script2 = 'AME51728LUShmUQMZM'
K>> evalin('caller', strcat(script2, ';'))
hi
```

Turns out with the underscore it works fine as well. MATLAB gives the following warning when renaming:

![image](https://user-images.githubusercontent.com/37122852/81320429-7709a580-9091-11ea-95c1-24ed40e6319d.png)

I modified runInFolder.m to remove the dashes before the run call:

```
function runInFolder(file, folder)
    % This ensures that the folder is removed from the path even if the function fails
    cleaner = onCleanup(@() rmpath(folder));
    addpath(folder);
    
    % Remove dashes ('-') from temp file name
    nfile = erase(file, '-');
    movefile(file, nfile);
    
    evalin('caller', ['run(''', nfile, ''')']);
end
```

A simple `disp('hi')` now works from Atom!

**Comment by elpollodiablo84** [comment]
Ok, that's interesting and unexpected. Next week I will try to dig deeper into this issue, since I think it's strange that it affects only R2019b. We'll see!
Thank you!

P.S.: I don't have access to Matlab until next week, but if you find something new or if you want to make a PR, let me know!

**Comment by elpollodiablo84** [comment]
I've just pushed a commit with a more robust management of temporary files. Since the reproduction of this issue is quite problematic, I would ask you to try again with this last version. It's not released on `apm`, so you need to use `git` to get it. If that is a problem, instead you can replace `atom-matlab-editor.js` with the new one, since it's the only file that I modified.
Let me know what happens.

P.S.: The issue doesn't seem linked to a Matlab version, but probably to some OS/date/dunnowhat combination of factors. The problem is that the the temporary file generator (`tmp`), in your case, chooses always a name with an hyphen `-` :shrug:

**Comment by elpollodiablo84** [comment]
Since this commit fixes some problems (I don't know if it fixes THIS problem), I'm going to push a new release with it.
I'll keep this issue open for some time, in case somebody finds some other complications.
